<?php echo $this->doctype(); ?>
<html lang="ru">

  <head>
  
    <meta charset="utf-8">
    
    <?php echo $this->headTitle('Линейный раскрой')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        //->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        //->appendStylesheet($this->basePath() . '/css/style.css')
        //->appendStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        ->appendStylesheet($this->basePath() . '/js/extjs/resources/css/ext-all.css') 
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        //->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        //->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') 
        ->appendFile($this->basePath() . '/js/extjs/ext-all.js')
        ->appendFile($this->basePath() . '/js/extjs/locale/ext-lang-ru.js')
        ->appendFile($this->basePath() . '/js/lincut/lang-ru.js')
        ->appendFile($this->basePath() . '/js/lincut/app.js');
    ?>

  </head>

  <body>
    
    
    
  </body>
  
</html>

